// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "data-automation-service/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// ReportRepository is an autogenerated mock type for the ReportRepository type
type ReportRepository struct {
	mock.Mock
}

// GetDailySalesSummary provides a mock function with given fields: ctx, dateStr
func (_m *ReportRepository) GetDailySalesSummary(ctx context.Context, dateStr string) (*domain.DailySalesPayloadData, error) {
	ret := _m.Called(ctx, dateStr)

	if len(ret) == 0 {
		panic("no return value specified for GetDailySalesSummary")
	}

	var r0 *domain.DailySalesPayloadData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.DailySalesPayloadData, error)); ok {
		return rf(ctx, dateStr)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.DailySalesPayloadData); ok {
		r0 = rf(ctx, dateStr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.DailySalesPayloadData)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, dateStr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProductPerformanceReport provides a mock function with given fields: ctx
func (_m *ReportRepository) GetProductPerformanceReport(ctx context.Context) ([]domain.ProductPerformanceReport, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetProductPerformanceReport")
	}

	var r0 []domain.ProductPerformanceReport
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.ProductPerformanceReport, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.ProductPerformanceReport); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ProductPerformanceReport)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSalesTrendReport provides a mock function with given fields: ctx, days
func (_m *ReportRepository) GetSalesTrendReport(ctx context.Context, days int) ([]domain.SalesTrendReport, error) {
	ret := _m.Called(ctx, days)

	if len(ret) == 0 {
		panic("no return value specified for GetSalesTrendReport")
	}

	var r0 []domain.SalesTrendReport
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]domain.SalesTrendReport, error)); ok {
		return rf(ctx, days)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []domain.SalesTrendReport); ok {
		r0 = rf(ctx, days)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.SalesTrendReport)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, days)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewReportRepository creates a new instance of ReportRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReportRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReportRepository {
	mock := &ReportRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
